CREATE TABLE Staff
(
 StaffNum SMALLINT NOT NULL IDENTITY,
 StaffName VARCHAR(50) NOT NULL,
 PRIMARY KEY (StaffNum)
);

CREATE TABLE Category
(
 CatName VARCHAR(50) NOT NULL,
 CatInfo TEXT,
 CatPicFile VARCHAR(200),
 PRIMARY KEY (CatName)
);

CREATE TABLE Orders
(
 OrderNum INT NOT NULL IDENTITY,
 TableNum TINYINT NOT NULL,
 Completed BIT NOT NULL DEFAULT 0,
 TotalPrice SMALLMONEY NOT NULL,
 OrderTime DATETIME NOT NULL DEFAULT (GETDATE()),
 StaffNum SMALLINT NOT NULL,
 PRIMARY KEY (OrderNum)
);

CREATE TABLE Item
(
 ItemNum SMALLINT NOT NULL IDENTITY,
 ItemName VARCHAR(50) NOT NULL,
 ItemInfo TEXT,
 ItemPicFile VARCHAR(200),
 OnSale BIT NOT NULL DEFAULT 0,
 ItemPrice SMALLMONEY NOT NULL,
 CatName VARCHAR(50) NOT NULL,
 PRIMARY KEY (ItemNum)
);

CREATE TABLE ItemOrder
(
 OrderNum INT NOT NULL,
 ItemNum SMALLINT NOT NULL,
 Quantity TINYINT NOT NULL,
 PRIMARY KEY (OrderNum, ItemNum)
);

ALTER TABLE Orders
 ADD CONSTRAINT OrdersStaff
 FOREIGN KEY (StaffNum) REFERENCES Staff(StaffNum);

ALTER TABLE Item
 ADD CONSTRAINT ItemCat
 FOREIGN KEY (CatName) REFERENCES Category(CatName);